use vulnerabilities;

create table label_encoder_cvss20 (id int auto_increment primary key, AV TINYINT UNSIGNED, AC TINYINT UNSIGNED, AU TINYINT UNSIGNED,
 C TINYINT UNSIGNED, I TINYINT UNSIGNED, A TINYINT UNSIGNED);
 
create table label_encoder_cvss30 (id int auto_increment primary key,
AV TINYINT UNSIGNED, AC TINYINT UNSIGNED, PR TINYINT UNSIGNED, UI TINYINT UNSIGNED, S TINYINT UNSIGNED,
C TINYINT UNSIGNED, I TINYINT UNSIGNED, A TINYINT UNSIGNED);

create table label_encoder_cvss31 (id int auto_increment primary key,
 AV TINYINT UNSIGNED, AC TINYINT UNSIGNED, PR TINYINT UNSIGNED, UI TINYINT UNSIGNED, S TINYINT UNSIGNED,
C TINYINT UNSIGNED, I TINYINT UNSIGNED, A TINYINT UNSIGNED);
